### ISSUE TITLE
Documentation / cleanup on the Machine/Distro/Image dichotomy

### ISSUE THREAD

**Issue by insatomcat** [seapath/meta-seapath#28]
On the documentation part: Is there a explaination on the different machines supported by the seapath project?
And distros ? and images ?
What features are supported by what category ?
A table to grasp the project choices would be very helping.

On the cleanup part:
Do we still need the votp-nuc machine ? Is is relevant to have a specific observer machine definition ? shouldn't it be a distro distinction ?
Do you think some feature that are currently in one category (image, distro or machine) should be moved to another ?
Any thought on this ?
Thanks.

**Comment by salerio-gs** [comment]
Regarding the votp-nuc machine. I introduced this to allow exploration of the distro on an Intel NUC. The reason it was added was because a) it followed the pattern and b) a kernel configuration item (https://github.com/seapath/meta-seapath/blob/main/recipes-kernel/linux/linux-mainline-rt/intel-nuc.cfg) was missing.
I guess this could be added as standard?

**Comment by insatomcat** [comment]
I can't see why not indeed.
I just opened #38 for this.
Thanks!
