### ISSUE TITLE
Create a Sandbox distribution 

### ISSUE THREAD

**Issue by watare** [seapath/meta-seapath#29]
Create a dedicated distribution + image without any security mechanism implemented:

- root login with a generic password for the first connection
- ssh login with password authentification 
- …

**Comment by watare** [comment]
Add a sandbox distribution without clustering

**Comment by ebail** [comment]
We will add DISTRO_FEATURES that enable / disable:

- security
- readonly filesystem
- clustering

Seapath Yocto distro will include those features while a minimal distro without those features will be created.
Cukinia tests will be split so that relevant tests would be installed depending on the DISTRO_FEATURES set.
